{% set name = "python-hcl2" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-hcl2-{{ version }}.tar.gz
  sha256: 0c79e2e4d14ec61110955ac1c6f504a2a5522e66e6dc598434e10c35e32d245d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - lark-parser >=0.10.0,<0.11.0
    - python >={{ python_min }}

test:
  imports:
    - hcl2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/amplify-education/python-hcl2
  summary: A parser for HCL2
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
