{% set name = "python-hcl2" %}
{% set version = "4.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-hcl2-{{ version }}.tar.gz
  sha256: e1f9eb9a55d751cb2c8bc410639d248f2ede7ea86d83ae9bc1cf8c8d0e74e794

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lark-parser >=0.10.0,<0.11.0
    - python >=3.6

test:
  imports:
    - hcl2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amplify-education/python-hcl2
  summary: A parser for HCL2
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
